# Longer words where shorter ones would do just as well
big_boy_words = [
    ['accordingly', 'so'],
    ['accumulate', 'gather'],
    ['acquire', 'get'],
    ['aggregate', 'total'],
    ['assist', 'help'],
    ['communicate', ['write', 'talk', 'tell']],
    ['compensation', 'pay'],
    ['consequently', 'so'],
    ['continue', 'keep up'],
    ['demonstrate', 'show'],
    ['discontinue', 'stop'],
    ['endeavor', 'try'],
    ['facilitate', ['ease', 'simplify']],
    ['hence', 'so'],
    ['implement', 'carry out'],
    ['initiate', 'carry out'],
    ['maximum', 'most'],
    ['modification', 'change'],
    ['nevertheless', ['but', 'however']],
    ['objective', 'aim'],
    ['optimum', 'best'],
    ['personnel', ['people', 'staff']],
    ['procure', ['get']],
    ['purchase', 'buy'],
    ['terminate', 'end'],
    ['transmit', 'end'],
    ['utilize', 'use'],
]

# Words that add nothing to the meaning of the sentence
dead_phrases = [
    'to the extent that',
    'with your permission',
    'hence',
    'with reference to',
    'in connection with',
    'with respect to',
    'as already stated',
    'in view of',
    'inasmuch as',
    'as a matter of fact',
    'for the purpose of',
]

# Words that can sound knowledgeable without being specific
buzz_words = [
    'parameters',
    'logistical interface',
    'contact',
    'warrants further investigation',
    'broad-based',
    'dynamics',
    'impact',
    'input/output',
    'conceptualize',
    'formalize',
    'multifaceted',
    'systematized',
    'prioritize',
    'time frame',
    'hard date',
    'in-depth study',
    'infrastructure',
    'longitudinal study',
    'matrix',
    'meaningful',
    'monolithic',
    'paradigm',
    'participatory involvement',
    'resource utilization',
    'viability',
]

# Anti-oxymoron
redundant_phrases = [
    'absolutely complete',
    'absolutely essential',
    'agreeable and satisfactory',
    'anxious and eager',
    'basic fundamentals',
    'complete absence',
    'consensus of opinion',
    'each and every',
    'exactly identical',
    'example to illustrate',
    'few in number',
    'first and foremost',
    'general consensus',
    'green in color',
    'human volunteer',
    'insist and demand',
    'my personal opinion',
    'necessary essentially',
    'past memories',
    'point in time',
    'right and proper',
    'sincere and earnest',
    'small in size',
    'summarize briefly',
    'thought and consideration',
    'true facts',
    'very unique',
]

# Phrases of serious business
business_jargon = [
    ['consideration was given', 'I considered'],
    ['prior to the', 'before'],
    ['at the present writing', 'now'],
    ['effect an improvement', 'improve'],
    ['in the neighborhood of', 'about'],
    ['beg to advise', 'tell'],
    ['cognizant of', 'know'],
    ['thanking you in advance', 'I would appreciate'],
    ['endeavor', 'try'],
    ['viable alternative', 'possibility'],
    ['in regard', 'about'],
    ['in reference to', 'about'],
    ['send under separate cover', 'send separately'],
    ['return same to the above', 'return to use'],
    ['needless to say', ''],
    ['it goes without saying', ''],
    ['in the normal course of procedure', 'normally'],
    ['in this day and age', 'today'],
    ['in my opinion', 'I believe'],
    ['it is our opinion', 'we think'],
    ['on a daily basis', 'daily'],
    ['on the grounds that', 'because'],
    ['pursuant to our agreement', 'as we agreed'],
    ['we are no in a position to', 'we cannot'],
    ['without further delay', 'now'],
    ['please be advised that', ''],
]
